# Generated by Django 2.0.1 on 2018-04-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_auto_20170713_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationLists',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'publications_publication_lists',
                'managed': False,
            },
        ),
    ]
